
POST http://localhost:3000/api/submit HTTP/1.1
Content-Type: application/json

{
    "language": "python3",
    "base64EncodedCode": "ZGVmIHByaW1lKHgsIHkpOgogICAgcHJpbWVfbGlzdCA9IFtdCiAgICBmb3IgaSBpbiByYW5nZSh4LCB5KToKICAgICAgICBpZiBpID09IDAgb3IgaSA9PSAxOgogICAgICAgICAgICBjb250aW51ZQogICAgICAgIGVsc2U6CiAgICAgICAgICAgIGZvciBqIGluIHJhbmdlKDIsIGludChpLzIpKzEpOgogICAgICAgICAgICAgICAgaWYgaSAlIGogPT0gMDoKICAgICAgICAgICAgICAgICAgICBicmVhawogICAgICAgICAgICBlbHNlOgogICAgICAgICAgICAgICAgcHJpbWVfbGlzdC5hcHBlbmQoaSkKICAgIHJldHVybiBwcmltZV9saXN0CgoKaWYgX19uYW1lX18gPT0gIl9fbWFpbl9fIjoKICAgIHN0YXJ0aW5nX3JhbmdlID0gOTkKICAgIGVuZGluZ19yYW5nZSA9IDEwMDAKICAgIGxzdCA9IHByaW1lKHN0YXJ0aW5nX3JhbmdlLCBlbmRpbmdfcmFuZ2UpCiAgICAKICAgIGlmIGxlbihsc3QpID09IDA6CiAgICAgICAgcHJpbnQoIlRoZXJlIGFyZSBubyBwcmltZSBudW1iZXJzIGluIHRoaXMgcmFuZ2UiKQogICAgZWxzZToKICAgICAgICBwcmludCgiVGhlIHByaW1lIG51bWJlcnMgaW4gdGhpcyByYW5nZSBhcmU6ICIsIGxzdCk="
}

POST http://localhost:3000/api/submit HTTP/1.1
Content-Type: application/json

{
    "language": "java",
    "base64EncodedCode": "Ly8gVGhpcyBpcyBhIHNpbXBsZSBKYXZhIHByb2dyYW0uCi8vIEZpbGVOYW1lIDogIkhlbGxvV29ybGQuamF2YSIuCgpwdWJsaWMgY2xhc3MgSGVsbG9Xb3JsZCB7CiAgICAvLyBZb3VyIHByb2dyYW0gYmVnaW5zIHdpdGggYSBjYWxsIHRvIG1haW4oKS4KICAgIC8vIFByaW50cyAiSGVsbG8sIFdvcmxkIiB0byB0aGUgdGVybWluYWwgd2luZG93LgogICAgcHVibGljIHN0YXRpYyB2b2lkIG1haW4oU3RyaW5nW10gYXJncykKICAgIHsKICAgICAgICBTeXN0ZW0ub3V0LnByaW50bG4oIkhlbGxvLCBXb3JsZCIpOwogICAgfQp9"
}

POST http://localhost:3000/api/submit HTTP/1.1
Content-Type: application/json

{
    "language": "python3",
    "base64EncodedCode": "ZGVmIHByaW1lKHgsIHkpOgogICAgcHJpbWVfbGlzdCA9IFtdCiAgICBmb3IgaSBpbiByYW5nZSh4LCB5KToKICAgICAgICBpZiBpID09IDAgb3IgaSA9PSAxOgogICAgICAgICAgICBjb250aW51ZQogICAgICAgIGVsc2U6CiAgICAgICAgICAgIGZvciBqIGluIHJhbmdlKDIsIGludChpLzIpKzEpOgogICAgICAgICAgICAgICAgaWYgaSAlIChqLzApID09IDA6CiAgICAgICAgICAgICAgICAgICAgYnJlYWsKICAgICAgICAgICAgZWxzZToKICAgICAgICAgICAgICAgIHByaW1lX2xpc3QuYXBwZW5kKGkpCiAgICByZXR1cm4gcHJpbWVfbGlzdAoKCmlmIF9fbmFtZV9fID09ICJfX21haW5fXyI6CiAgICBzdGFydGluZ19yYW5nZSA9IDk5CiAgICBlbmRpbmdfcmFuZ2UgPSAxMDAwCiAgICBsc3QgPSBwcmltZShzdGFydGluZ19yYW5nZSwgZW5kaW5nX3JhbmdlKQogICAgCiAgICBpZiBsZW4obHN0KSA9PSAwOgogICAgICAgIHByaW50KCJUaGVyZSBhcmUgbm8gcHJpbWUgbnVtYmVycyBpbiB0aGlzIHJhbmdlIikKICAgIGVsc2U6CiAgICAgICAgcHJpbnQoIlRoZSBwcmltZSBudW1iZXJzIGluIHRoaXMgcmFuZ2UgYXJlOiAiLCBsc3Qp"
}